name: CI

on:
  push:
    branches:
      - main
      - krb-*
      - KRB-*
    tags:
      - .+

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.5

      - name: Build with Maven
        run: make build

      - name: Upload target
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: target
          retention-days: 1

  docker:
    name: Docker
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download target
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - name: Build docker image
        run: make docker

      - name: Login to GitHub Container Registry
        if: "startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker image (commit)
        if: "startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'"
        run: make docker-push

      - name: Push docker-image (main)
        if: "github.ref == 'refs/heads/main'"
        run:
          make docker-tag version=main
          make docker-push version=main

      - name: Push docker image (release)
        if: "startsWith(github.ref, 'refs/tags/')"
        run: |
          make docker-tag version=latest
          make docker-push version=latest